<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users Report</title>
</head>
<body>
    <div style="margin-bottom:25px;"><strong>Report generated by: </strong></div>
    <table style="border-collapse: collapse;">
        <thead>
            <tr>
                <th style="border-bottom:2pt solid black;">
                    <strong>OS</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Equipamento</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Identificação</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Item</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Proxima</strong>
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach ($maintenances as $maintenance)
            <tr>
                <td style="border-bottom:1pt solid black;">
                    {{ $maintenance['service_order_id'] }}
                </td>
                <td style="border-bottom:1pt solid black;">
                    {{ $maintenance['equipment_id'] }}
                </td>
                <td style="border-bottom:1pt solid black;">
                    {{ $maintenance['identification'] }}
                </td>
                <td style="border-bottom:1pt solid black;">
                    {{ $maintenance['part_id'] }}
                </td>
                <td style="border-bottom:1pt solid black;">
                    {{ $maintenance['next_maintenance'] }}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</body>
</html>