<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users Report</title>
</head>
<body>
    <div style="margin-bottom:25px;"><strong>Report generated by: </strong></div>
    <table style="border-collapse: collapse;">
        <thead>
            <tr>
                <th style="border-bottom:2pt solid black;">
                    <strong>OS</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Equipamento</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Identificação</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Item</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Proxima</strong>
                </th>
            </tr>
        </thead>
        <tbody>
        <?php $__currentLoopData = $maintenances; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $maintenance): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td style="border-bottom:1pt solid black;">
                    <?php echo e($maintenance['service_order_id']); ?>

                </td>
                <td style="border-bottom:1pt solid black;">
                    <?php echo e($maintenance['equipment_id']); ?>

                </td>
                <td style="border-bottom:1pt solid black;">
                    <?php echo e($maintenance['identification']); ?>

                </td>
                <td style="border-bottom:1pt solid black;">
                    <?php echo e($maintenance['part_id']); ?>

                </td>
                <td style="border-bottom:1pt solid black;">
                    <?php echo e($maintenance['next_maintenance']); ?>

                </td>
            </tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>
</body>
</html><?php /**PATH /var/www/html/resources/views/report.blade.php ENDPATH**/ ?>